volumes:
  maven-repo:

services:
  web:
    image: library/maven:3.6.3-openjdk-14
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=mysql
      - MYSQL_URL=jdbc:mysql://mysql/petclinic
    working_dir: "/app"
    volumes:
      - ".:/app"
      - "maven-repo:/root/.m2"
    command: "mvn spring-boot:run"

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
